const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const {launch}=require('./browser.cjs');
const seed=require('./catalog-seed.json');
const DAY=86400000;
const validId=id=>Number.isSafeInteger(id)&&id>0&&id<=0xffffffff;
function normalize(s){return s.toLowerCase().replace(/[^a-z0-9]/g,'');}
const extractCatalog=`(()=>{const out=[];for(const row of document.querySelectorAll('.itemnav-tier-row')){if(row.querySelector('.itemnav-legendary'))continue;for(const el of row.querySelectorAll('.item-nav-search-item')){const name=el.getAttribute('data-item-name');const a=el.querySelector('a[href]');if(!name||name.startsWith('upgrade_')||!a||/enhanced|street brawl/i.test(el.textContent))continue;const url=new URL(a.getAttribute('href'),location.href);if(url.origin===location.origin)out.push({name,source:url.origin+url.pathname});}}return out;})()`;
const extractCard=`(async()=>{const t=document.querySelector('#tabber-Default table.item-infobox')||document.querySelector('table.item-infobox');if(!t)throw Error('Wiki card is unavailable');if(t.querySelector('.enhanced-label,.legendary-label,.street-brawl-label'))throw Error('Excluded item variant');for(const e of t.querySelectorAll('.codename,.sounds-header,.sound-item,.components-header,.is-component-of-header'))e.closest('tr')?.remove();for(const e of t.querySelectorAll('script,audio,video'))e.remove();for(const e of t.querySelectorAll('tr'))if(!e.textContent.trim()&&!e.querySelector('img'))e.remove();for(const img of t.querySelectorAll('img')){img.loading='eager';img.removeAttribute('srcset');}for(const style of document.body.querySelectorAll('style'))document.head.appendChild(style.cloneNode(true));const clean=document.createElement('style');clean.textContent='html::before,html::after,body::before,body::after{display:none!important}';document.head.appendChild(clean);const clone=t.cloneNode(true);const wrapper=document.createElement('div');wrapper.className='mw-parser-output';const inner=document.createElement('div');inner.className='infobox_item';inner.style.cssText='margin:0!important;float:none!important';inner.appendChild(clone);wrapper.appendChild(inner);document.body.replaceChildren(wrapper);document.documentElement.style.cssText='background:transparent!important';document.body.style.cssText='margin:0!important;padding:0!important;background:transparent!important;min-width:0!important';clone.style.cssText+=';position:absolute!important;left:0!important;top:0!important;margin:0!important;width:312px!important;min-width:312px!important;max-width:312px!important;font-family:Retail Demo,sans-serif;font-size:14px;line-height:1.6';await Promise.all([...clone.querySelectorAll('img')].map(i=>i.complete?Promise.resolve():new Promise(r=>{i.onload=r;i.onerror=r;setTimeout(r,8000);})));await document.fonts.ready;const failed=[...clone.querySelectorAll('img')].filter(i=>!i.naturalWidth);if(failed.length)throw Error('Wiki card images failed to load');const r=clone.getBoundingClientRect();if(r.height<100||r.height>3000)throw Error('Unexpected card size');return {x:0,y:0,width:Math.ceil(r.width),height:Math.ceil(r.height),title:clone.innerText.slice(0,150)};})()`;
async function atomic(file,data){await fs.mkdir(path.dirname(file),{recursive:true});const temp=file+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(temp,data);await fs.rename(temp,file);}
class CardStore {
  constructor(root,options={}){this.root=root;this.strictCatalog=options.strictCatalog===true;this.browserFactory=options.browserFactory||launch;this.fetch=options.fetch||fetch;this.browser=null;this.queue=Promise.resolve();this.catalog=seed.map(x=>({...x,file:`Cards/${x.itemId}.png`,mode:'normal',variant:'default'}));}
  serial(fn){const job=this.queue.then(fn);this.queue=job.catch(()=>{});return job;}
  async getBrowser(){return this.browser||(this.browser=await this.browserFactory());}
  async read(file){try{return JSON.parse(await fs.readFile(path.join(this.root,file),'utf8'));}catch{return null;}}
  async loadCatalog(){const saved=await this.read('catalog.json');if(saved?.items?.length>=50)this.catalog=saved.items;return this.catalog;}
  async refreshCatalog(force=false){return this.serial(async()=>{const saved=await this.read('catalog.json');if(!force&&saved&&Date.now()-saved.checkedAt<DAY){this.catalog=saved.items;return {items:this.catalog,offline:false};}try{const response=await this.fetch('https://api.deadlock-api.com/v1/assets/items',{signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('Item service unavailable');const assets=await response.json();const b=await this.getBrowser();await b.page('https://deadlock.wiki/Items');const wiki=await b.evaluate(extractCatalog);if(wiki.length<50)throw new Error('Wiki catalog layout changed');const byName=new Map(assets.filter(x=>x.type==='upgrade'&&validId(x.id)).map(x=>[normalize(x.name),x]));const seen=new Set();const items=[];for(const w of wiki){const a=byName.get(normalize(w.name));if(!a){if(this.strictCatalog)throw Error('Unresolved wiki item identity: '+w.name);continue;}if(seen.has(a.id))continue;seen.add(a.id);items.push({itemId:a.id,name:w.name,source:w.source,file:`Cards/${a.id}.png`,mode:'normal',variant:'default'});}if(items.length<50||items.length<this.catalog.length*.8)throw new Error('Wiki catalog could not be verified');this.catalog=items;await atomic(path.join(this.root,'catalog.json'),JSON.stringify({checkedAt:Date.now(),items}));return {items,offline:false};}catch(e){await this.loadCatalog();return {items:this.catalog,offline:true,warning:e.message};}});}
  async prepare(id,force=false){if(!validId(id))throw new Error('Invalid item ID');return this.serial(async()=>{const item=this.catalog.find(x=>x.itemId===id);if(!item)throw new Error('Item is not in the normal-mode catalog');const cached=await this.read(`items/${id}.json`);const usable=async()=>{if(!cached||!/^([a-f0-9]{64})\.png$/.test(cached.asset))return false;try{const bytes=await fs.readFile(path.join(this.root,'assets',cached.asset));return crypto.createHash('sha256').update(bytes).digest('hex')+'.png'===cached.asset;}catch{return false;}};const have=await usable();if(have&&!force&&Date.now()-cached.checkedAt<DAY)return {...cached,cached:true};try{const b=await this.getBrowser();await b.page(item.source);const clip=await b.evaluate(extractCard);const bytes=await b.screenshot({x:clip.x,y:clip.y,width:clip.width,height:clip.height});if(bytes.length<1000||bytes.readUInt32BE(0)!==0x89504e47)throw new Error('Invalid rendered card');const width=bytes.readUInt32BE(16),height=bytes.readUInt32BE(20);const hash=crypto.createHash('sha256').update(bytes).digest('hex'),asset=hash+'.png';await atomic(path.join(this.root,'assets',asset),bytes);const meta={...item,asset,width,height,checkedAt:Date.now(),source:item.source,attribution:'Deadlock Wiki contributors; wiki text CC BY-NC-SA 4.0. Game artwork has separate rights.'};await atomic(path.join(this.root,`items/${id}.json`),JSON.stringify(meta));return {...meta,cached:false};}catch(e){if(have)return {...cached,cached:true,offline:true,warning:e.message};throw e;}});}
  async close(){await this.queue;await this.browser?.close();this.browser=null;}
}
module.exports={CardStore,validId,extractCard,extractCatalog};
